

baseURL = "https://example.com"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Older Guy, LISPing from time to time."
theme = "beautifulhugo"
author = "Tom Rake"
hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
[frontmatter]
  date = [':filename', ':default']
  lastmod = ['lastmod', ':fileModTime']

[params.author]
name = "Tom Rake"
email = "tom.rake@gmail.com"
github = "tomrake"
bluesky = "tomrake"

[[menu.main]]
name = "About Me"
url = "about"
mastodon = "mastodon.social/@tomrake"

[[menu.main]]
name = "Projects"
identifier = "projects"

[[menu.main]]
parent = "projects"
name = "The-Invaders"
url = "https://tomrake.github.io/the-invaders/"
[[menu.main]]
parent = "projects"
name = "My Project Skel"
url = "https://tomrake.github.io/my-project-skel/"

[[menu.main]]
parent = "projects"
name  = "SDL-Loader"
url = "https://tomrake.github.io/sdl-loader/"

[[menu.main]]
name = "LISP Resources"
identifier = "lisp-resources"

[[menu.main]]
parent = "lisp-resources"
name = "SBCL"
url = "https://www.sbcl.org"
[[menu.main]]
parent = "lisp-resources"
name = "emacs"
url = "https://www.gnu.org/software/emacs/"
[[menu.main]]
parent = "lisp-resources"
name = "quicklisp"
url = "https://www.quicklisp.org/beta/"

[[menu.main]]

parent = "lisp-resources"
name = "Common-Lisp-On-Reddit"
url ="https://www.reddit.com/r/common_lisp"


[params]

    # Source Code repository section
    description = "The Blog of Tom Rake"
    github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    version = "1.0.1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/tomrake/test-blog"
    github_doc_repository_branch = "master"
    github_doc_repository_path = ""

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Hugo Techdoc Theme"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable = true
    algolia_indexName = "hugo-demo-techdoc"
    algolia_appId = "7W4SAN4PLK"
    algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = 'home'
        pre = "<i class='fa fa-heart'></i>&nbsp;"


# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]

