

baseURL = "https://tomrake.github.io"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "LISPing and misc."
theme = "beautifulhugo"
author = "Tom Rake"
hasCJKLanguage = true
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsUseClasses = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
[frontmatter]
  date = [':filename', ':default']
  lastmod = ['lastmod', ':fileModTime']

[params.author]
name = "Tom Rake"
email = "tom.rake@gmail.com"
github = "tomrake"
bluesky = "tomrake"
facebook = "tom.rake"
mastodon = "mastodon.social/@tomrake"
[[menu.main]]
name = "About Me"
url = "about"
weight = 10

[[menu.main]]
name = "Projects"
identifier = "projects"
weight = 20

[[menu.main]]
parent = "projects"
name = "The-Invaders"
url = "https://tomrake.github.io/the-invaders/"
[[menu.main]]
parent = "projects"
name = "My Project Skel"
url = "https://tomrake.github.io/my-project-skel/"

[[menu.main]]
parent = "projects"
name  = "SDL-Loader"
url = "https://tomrake.github.io/sdl-loader/"

[[menu.main]]
name = "LISP Resources"
identifier = "lisp-resources"
weight = 30

[[menu.main]]
parent = "lisp-resources"
name = "SBCL"
url = "https://www.sbcl.org"
[[menu.main]]
parent = "lisp-resources"
name = "emacs"
url = "https://www.gnu.org/software/emacs/"
[[menu.main]]
parent = "lisp-resources"
name = "quicklisp"
url = "https://www.quicklisp.org/beta/"

[[menu.main]]

parent = "lisp-resources"
name = "Common-Lisp-On-Reddit"
url ="https://www.reddit.com/r/common_lisp"

[[menu.main]]
name = "Theme"
identifier = "theme"

[[menu.main]]
parent = "theme"
name = "Beautiful Hugo"
url = "https://github.com/tomrake/beautifulhugo"


# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "home"
        url = "/"
        weight = 1
        identifier = 'home'
        pre = "<i class='fa fa-heart'></i>&nbsp;"
[[menu.main]]
parent = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
parent = "home"
name = "Blog"
url = "/blog/"
weight = 20

[[menu.main]]
parent = "home"
name = "Legacy Blog"
url = "/legacy/"
weight = 30

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS"]

